Repository AhmedRaisi/Tarsho, pull requests merged in 2023-12, with the labels that each got.

#102 Login-SignUp-UI-Changes
  web/src/components/pages/home/LoginModal.jsx
  web/src/components/pages/home/RegisterModal.jsx
  web/src/components/pages/home/styles.css
Labels: frontend, UI/UX

#104 feat: add show more button to client and provider
  web/public/index.html
  web/src/components/pages/client/dashboard/ClientDashboard.css
  web/src/components/pages/client/dashboard/ClientDashboard.jsx
  web/src/components/pages/client/services/ClientServicesPages.css
  web/src/components/pages/client/services/ClientServicesPages.jsx
  web/src/components/pages/provider/dashboard/ProviderDashboard.jsx
Labels: feature, frontend

#111 GraphQL Implementation and RestfulAPI replacement.
  .husky/pre-commit
  package-lock.json
  package.json
  server/app.js
  server/graphql/resolvers.js
  server/graphql/schema.js
  server/graphql/serviceType.js
  server/graphql/userType.js
  server/models/User.js
  server/models/service.js
  server/nodemon.js
  server/package-lock.json
  server/package.json
  server/routes/users.js
  web/package-lock.json
  web/package.json
  web/src/app.test.js
  web/src/app.test.jsx
  web/src/components/pages/client/dashboard/ClientDashboard.jsx
  web/src/components/pages/client/profile/ClientProfilePage.css
  web/src/components/pages/client/profile/ClientProfilePage.jsx
  web/src/components/pages/client/profile/EditClientProfileModal.jsx
  web/src/components/pages/client/services/ClientServicesPages.css
  web/src/components/pages/client/services/ClientServicesPages.jsx
  web/src/components/pages/home/LoginModal.jsx
  web/src/components/pages/home/RegisterModal.jsx
  web/src/components/pages/home/styles.css
  web/src/components/pages/provider/dashboard/ProviderDashboard.jsx
  web/src/components/pages/provider/hf/header/headstyles.css
  web/src/components/pages/provider/profile/EditProviderProfileModal.jsx
  web/src/components/pages/provider/profile/ProviderProfilePage.jsx
  web/src/components/pages/provider/services/AddServiceProviderModal.jsx
  web/src/components/pages/provider/services/ProviderServicesPage.jsx
Labels: backend, dont merge

#115 Registeration fixed
  server/graphql/resolvers.js
  server/graphql/schema.js
  server/graphql/userType.js
  server/models/User.js
  web/src/components/pages/home/RegisterModal.jsx
  web/src/components/pages/home/hf/header/header.jsx
Labels: bug, backend

#116 fixed profiles
  package-lock.json
  package.json
  prepare.js
  web/package-lock.json
  web/src/components/pages/client/profile/ClientProfilePage.jsx
  web/src/components/pages/client/profile/ClientProviderProfile.jsx
  web/src/components/pages/provider/profile/ProviderProfilePage.jsx
Labels: bug, backend
